<?php

return [
    'Adjusting Bell Curves',
    'Aesthesizing Industrial Areas',
    'Aligning Covariance Matrices',
    'Applying Feng Shui Shaders',
    'Applying Theatre Soda Layer',
    'Asserting Packed Exemplars',
    'Attempting to Lock Back-Buffer',
    'Binding Sapling Root System',
    'Breeding Fauna',
    'Building Data Trees',
    'Bureacritizing Bureaucracies',
    'Calculating Inverse Probability Matrices',
    'Calculating Llama Expectoration Trajectory',
    'Calibrating Blue Skies',
    'Charging Ozone Layer',
    'Coalescing Cloud Formations',
    'Cohorting Exemplars',
    'Collecting Meteor Particles',
    'Compounding Inert Tessellations',
    'Compressing Fish Files',
    'Computing Optimal Bin Packing',
    'Concatenating Sub-Contractors',
    'Containing Existential Buffer',
    'Debarking Ark Ramp',
    'Debunching Unionized Commercial Services',
    'Deciding What Message to Display Next',
    'Decomposing Singular Values',
    'Decrementing Tectonic Plates',
    'Deleting Ferry Routes',
    'Depixelating Inner Mountain Surface Back Faces',
    'Depositing Slush Funds',
    'Destabilizing Economic Indicators',
    'Determining Width of Blast Fronts',
    'Deunionizing Bulldozers',
    'Dicing Models',
    'Diluting Livestock Nutrition Variables',
    'Downloading Satellite Terrain Data',
    'Exposing Flash Variables to Streak System',
    'Extracting Resources',
    'Factoring Pay Scale',
    'Fixing Election Outcome Matrix',
    'Flood-Filling Ground Water',
    'Flushing Pipe Network',
    'Gathering Particle Sources',
    'Generating Jobs',
    'Gesticulating Mimes',
    'Graphing Whale Migration',
    'Hiding Willio Webnet Mask',
    'Implementing Impeachment Routine',
    'Increasing Accuracy of RCI Simulators',
    'Increasing Magmafacation',
    'Initializing My Sim Tracking Mechanism',
    'Initializing Rhinoceros Breeding Timetable',
    'Initializing Robotic Click-Path AI',
    'Inserting Sublimated Messages',
    'Integrating Curves',
    'Integrating Illumination Form Factors',
    'Integrating Population Graphs',
    'Iterating Cellular Automata',
    'Lecturing Errant Subsystems',
    'Mixing Genetic Pool',
    'Modeling Object Components',
    'Mopping Occupant Leaks',
    'Normalizing Power',
    'Obfuscating Quigley Matrix',
    'Overconstraining Dirty Industry Calculations',
    'Partitioning City Grid Singularities',
    'Perturbing Matrices',
    'Polishing Water Highlights',
    'Populating Lot Templates',
    'Preparing Sprites for Random Walks',
    'Prioritizing Landmarks',
    'Projecting Law Enforcement Pastry Intake',
    'Realigning Alternate Time Frames',
    'Reconfiguring User Mental Processes',
    'Relaxing Splines',
    'Removing Road Network Speed Bumps',
    'Removing Texture Gradients',
    'Removing Vehicle Avoidance Behavior',
    'Resolving GUID Conflict',
    'Reticulating Splines',
    'Retracting Phong Shader',
    'Retrieving from Back Store',
    'Reverse Engineering Image Consultant',
    'Routing Neural Network Infanstructure',
    'Scattering Rhino Food Sources',
    'Scrubbing Terrain',
    'Searching for Llamas',
    'Seeding Architecture Simulation Parameters',
    'Sequencing Particles',
    'Setting Advisor Moods',
    'Setting Inner Deity Indicators',
    'Setting Universal Physical Constants',
    'Sonically Enhancing Occupant-Free Timber',
    'Speculating Stock Market Indices',
    'Splatting Transforms',
    'Stratifying Ground Layers',
    'Sub-Sampling Water Data',
    'Synthesizing Gravity',
    'Synthesizing Wavelets',
    'Time-Compressing Simulator Clock',
    'Unable to Reveal Current Activity',
    'Weathering Buildings',
    'Zeroing Crime Network',
    "Reticulating splines...",
    "Generating witty dialog...",
    "Swapping time and space...",
    "Spinning violently around the y-axis...",
    "Tokenizing real life...",
    "Bending the spoon...",
    "Filtering morale...",
    "Don't think of purple hippos...",
    "We need a new fuse...",
    "Have a good day.",
    "640K ought to be enough for anybody",
    "The architects are still drafting",
    "We're building the buildings as fast as we can",
    "Would you prefer chicken, steak, or tofu?",
    "(Pay no attention to the man behind the curtain)",
    "...and enjoy the elevator music...",
    "Please wait while the little elves draw your map",
    "Don't worry - a few bits tried to escape, but we caught them",
    "Would you like fries with that?",
    "Checking the gravitational constant in your locale...",
    "...at least you're not on hold...",
    "Hum something loud while others stare",
    "The server is powered by a lemon and two electrodes.",
    "We're testing your patience",
    "Follow the white rabbit",
    "Why don't you order a sandwich?",
    "While the satellite moves into position",
    "The bits are flowing slowly today",
    "Dig on the 'X' for buried treasure... ARRR!",
    "It's still faster than you could draw it",
    "The last time I tried this the monkey didn't survive. Let's hope it works better this time.",
    "I should have had a V8 this morning.",
    "My other loading screen is much faster.",
    "Testing on Timmy... We're going to need another Timmy.",
    "Reconfoobling energymotron...",
    "(Insert quarter)",
    "Are we there yet?",
    "Have you lost weight?",
    "Just count to 10",
    "Why so serious?",
    "It's not you. It's me.",
    "Counting backwards from Infinity",
    "Don't panic...",
    "Embiggening Prototypes",
    "Do not run! We are your friends!",
    "Do you come here often?",
    "Warning: Don't set yourself on fire.",
    "We're making you a cookie.",
    "Creating time-loop inversion field",
    "Spinning the wheel of fortune...",
    "Loading the enchanted bunny...",
    "Computing chance of success",
    "I'm sorry Dave, I can't do that.",
    "Looking for exact change",
    "All your web browser are belong to us",
    "All I really need is a kilobit.",
    "I feel like im supposed to be loading something. . .",
    "What do you call 8 Hobbits? A Hobbyte.",
    "Should have used a compiled language...",
    "Is this Windows?",
    "Adjusting flux capacitor...",
    "Please wait until the sloth starts moving.",
    "Don't break your screen yet!",
    "I swear it's almost done.",
    "Let's take a mindfulness minute...",
    "Unicorns are at the end of this road, I promise.",
    "Listening for the sound of one hand clapping...",
    "Keeping all the 1's and removing all the 0's...",
    "Putting the icing on the cake. The cake is not a lie...",
    "Cleaning off the cobwebs...",
    "Making sure all the i's have dots...",
    "We need more dilithium crystals",
    "Where did all the internets go",
    "Connecting Neurotoxin Storage Tank...",
    "Granting wishes...",
    "Time flies when you’re having fun.",
    "Get some coffee and come back in ten minutes..",
    "Spinning the hamster…",
    "Stay awhile and listen..",
    "You shall not pass! yet..",
    "Load it and they will come",
    "Convincing AI not to turn evil..",
    "There is no spoon. Because we are not done loading it",
    "Your left thumb points to the right and your right thumb points to the left.",
    "How did you get here?",
    "Wait, do you smell something burning?",
    "Computing the secret to life, the universe, and everything.",
    "When nothing is going right, go left!!...",
    "Why are they called apartments if they are all stuck together?",
    "I’ve got a problem for your solution…..",
    "Adults are just kids with money.",
    "I think I am, therefore, I am. I think.",
    "Constructing additional pylons...",
    "Roping some seaturtles...",
    "Locating Jebediah Kerman...",
    "We are not liable for any broken screens as a result of waiting.",
    "Hello IT, have you tried turning it off and on again?",
    "If you type Google into Google you can break the internet",
    "What is the airspeed velocity of an unladen swallow?",
    "Hello, IT... Have you tried forcing an unexpected reboot?",
    "The Elders of the Internet would never stand for it.",
    "Space is invisible mind dust, and stars are but wishes.",
    "Didn't know paint dried so quickly.",
    "Everything sounds the same",
    "I'm going to walk the dog",
    "Dividing by zero...",
    "Spawn more Overlord!",
    "Some days, you just can’t get rid of a bug!",
    "We’re going to need a bigger boat.",
    "Cracking military-grade encryption...",
    "Simulating traveling salesman...",
    "Proving P=NP...",
    "Entangling superstrings...",
    "Twiddling thumbs...",
    "Searching for plot device...",
    "Trying to sort in O(n)...",
    "Sending data to NS-I mean, our servers.",
    "Looking for sense of humour, please hold on.",
    "Please wait while the intern refills his coffee.",
    "A different error message? Finally, some progress!",
    "Please hold on as we reheat our coffee",
    "Kindly hold on as our intern quits vim...",
    "Winter is coming...",
    "Installing dependencies",
    "Distracted by cat gifs",
    "BRB, working on my side project",
    "@todo Insert witty loading message",
    "Let's hope it's worth the wait",
    "Aw, snap! Not..",
    "Ordering 1s and 0s...",
    "Updating dependencies...",
    "Whatever you do, don't look behind you...",
    "Please wait... Consulting the manual...",
    "It is dark. You're likely to be eaten by a grue.",
    "Loading funny message...",
    "Waiting Daenerys say all her titles...",
    "Feel free to spin in your chair",
    "Forget you saw that password I just typed into the IM ...",
    "What's under there?",
    "Bored of slow loading spinner, buy more RAM!",
    "Help, I'm trapped in a loader!",
    "What is the difference between a hippo and a zippo? One is really heavy, the other is a little lighter",
    "Please wait, while we purge the Decepticons for you. Yes, You can thanks us later!",
    "Mining some bitcoins...",
    "Downloading more RAM..",
    "Initializing the initializer...",
    "When was the last time you dusted around here?",
    "Optimizing the optimizer...",
    "Last call for the data bus! All aboard!",
    "Running swag sticker detection...",
    "Never let a computer know you're in a hurry.",
    "A computer will do what you tell it to do, but that may be much different from what you had in mind.",
    "Some things man was never meant to know. For everything else, there's Google.",
    "Shovelling coal into the server",
    "Pushing pixels...",
    "How about this weather, eh?",
    "Building a wall...",
    "Everything in this universe is either a potato or not a potato",
    "The severity of your issue is always lower than you expected.",
    "Updating Updater...",
    "Downloading Downloader...",
    "Debugging Debugger...",
    "Reading Terms and Conditions for you.",
    "Digested cookies being baked again.",
    "Live long and prosper.",
    "There is no cow level, but there's a goat one!",
    "Running with scissors...",
    "You may call me Steve.",
    "You seem like a nice person...",
    "Work, work...",
    "Patience! This is difficult, you know...",
    "Discovering new ways of making you wait...",
    "Time flies like an arrow; fruit flies like a banana",
    "Two men walked into a bar; the third ducked...",
    "Sooooo... Have you seen my vacation photos yet?",
    "Sorry we are busy catching em' all, we're done soon",
    "TODO: Insert elevator music",
    "Still faster than Windows update",
    "Please wait while the minions do their work",
    "Grabbing extra minions",
    "Doing the heavy lifting",
    "We're working very Hard .... Really",
    "Waking up the minions",
    "You are number 2843684714 in the queue",
    "Please wait while we serve other customers...",
    "Our premium plan is faster",
    "Feeding unicorns...",
];
